version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - '3306:3306'
  node:
    image: node:16.14
    container_name: users_backend
    tty: true
    stdin_open: true
    command: bash -c "npm install && npx sequelize-cli db:create && npx sequelize db:migrate && npm run dev"

    restart: always
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: UsersDB
      MYSQL_HOST: db
      API_PORT: '3001'

  frontend:
    container_name: users_frontend
    image: node:16.14
    restart: always
    command: bash -c "npm install && npx ng serve --host=0.0.0.0 --disable-host-check"
    tty: true
    stdin_open: true
    expose:
      - 4200
    ports:
      - 4200:4200
    working_dir: /app-frontend
    volumes:
      - ./crud-angular:/app-frontend
    depends_on:
      - node
 
networks:
  default:
    name: users_net